Issue 42005: Merge additional wnprc18.3 SVN changes to Git for 21.3
LabKey/ehrModules pull request #133
Opened 2021-03-03 05:08 UTC by labkey-bpatel

#### Rationale
Issue [42005](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=42005): Merge additional wnprc18.3 SVN changes to Git for 21.3

#### Related Pull Requests
* 

#### Changes
Merge from wnprc18.3 svn r.65685 to 66153

2021-03-03 21:26 UTC, labkey-jeckels requested changes

2021-03-03 21:26 UTC, labkey-jeckels commented on ehr/resources/schemas/dbscripts/postgresql/ehr-20.001-20.002.sql
> +ALTER TABLE ehr.form_framework_types add column url varchar(255) DEFAULT NULL;
Won't think blow up on WNPRC's server because the column already exists?

2021-03-05 20:41 UTC, labkey-jeckels approved these changes

2021-03-15 04:32 UTC, labkey-bpatel commented
There is SNPRC test failure related to blood draws during study import  - see this closed PR for details and comments: https://github.com/LabKey/snprcEHRModules/pull/344

2021-03-15 04:32 UTC, merged