Created a new column to track training categories that are not requir…
LabKey/ehrModules pull request #186
Opened 2021-05-25 22:59 UTC by Ohsudev

…ed as training requirements. This set is for the EHR Module version of additional code.

#### Rationale

#### Related Pull Requests

#### Changes
Created a new column to track training categories that are not required as training requirements. This set is for the EHR Module version.  The other set of codes that complements this feature branch resides on "onprcEHRModules"/

2021-05-26 17:02 UTC, kollil approved these changes
Raymond, The changes look good.

2021-05-26 17:39 UTC, kollil reviewed
Raymond, I forgot to mention if the new db field is added to the ehr_compliancedb.xml file?

2021-05-26 17:42 UTC, labkey-jeckels requested changes
As Lakshmi commented, the new column should get an entry in ehr_compliancedb.xml

2021-05-26 17:42 UTC, labkey-jeckels commented on EHR_ComplianceDB/resources/schemas/dbscripts/sqlserver/EHR_ComplianceDB-12.40-12.41.sql
> +ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag varchar(100);
```suggestion
ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag nvarchar(100);
```

2021-05-26 18:18 UTC, Ohsudev commented
HI Josh.  Do I still need to make an entry into  “ehr_compliancedb.xml” despite having the following code already include into “onprcEHRModules” repository part of my feature branch?

C:\Test_20.11\server\modules\onprcEHRModules\ONPRC_EHR_ComplianceDB\resources\queries\EHR_ComplianceDB\RequirementsPerCategory.query.xml
    <column columnName="TrackingFlag">
                <isUserEditable>true</isUserEditable>
                <nullable>true</nullable>
                <isHidden>false</isHidden>
            </column>

Thanks,
Raymond

From: Josh Eckels ***@***.***>
Sent: Wednesday, May 26, 2021 10:43 AM
To: LabKey/ehrModules ***@***.***>
Cc: Raymond Blasa ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LabKey/ehrModules] Created a new column to track training categories that are not requir… (#186)


@labkey-jeckels requested changes on this pull request.

As Lakshmi commented, the new column should get an entry in ehr_compliancedb.xml

________________________________

In EHR_ComplianceDB/resources/schemas/dbscripts/sqlserver/EHR_ComplianceDB-12.40-12.41.sql<https://github.com/LabKey/ehrModules/pull/186#discussion_r639983816>:

> @@ -0,0 +1 @@



+ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag varchar(100);


⬇️ Suggested change

-ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag varchar(100);



+ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag nvarchar(100);



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/LabKey/ehrModules/pull/186#pullrequestreview-669363061>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASHU2YEMEX4G77YXGRFY5FTTPUXJHANCNFSM45QMEMKA>.

2021-05-26 20:14 UTC, labkey-jeckels commented
@Ohsudev yes, please. We have automated tests that compare the list of columns in the centralized schema XML file (ehr_compliancedb.xml in this case) against what's actually in the database. That helps us make sure that the Postgres and SQLServer versions of the schemas don't diverge for modules that support both DBs.

2021-05-26 20:36 UTC, Ohsudev commented
Added a new file as per Josh's and Lakshmi's  request to be included into this feature branch.  Please review again for me.

2021-05-26 21:20 UTC, labkey-jeckels approved these changes

2021-05-26 21:20 UTC, labkey-jeckels commented on EHR_ComplianceDB/resources/schemas/dbscripts/sqlserver/EHR_ComplianceDB-12.40-12.41.sql
> +ALTER TABLE ehr_compliancedb.RequirementsPerCategory add TrackingFlag varchar(100);
I'm going to go ahead and commit this suggested change.

2021-10-04 23:42 UTC, Ohsudev commented
No longer needed.

2021-10-04 23:42 UTC, closed without merging