Clinical remarks data source
LabKey/ehrModules pull request #250
Opened 2021-10-07 17:11 UTC by labkey-martyp

#### Rationale
Clinical remarks categories value can be an integer so try to use title if it's available, then fall back to value.  Also refresh EHR data entry cache when EHR lookup sets are updated.

#### Related Pull Requests
* https://github.com/LabKey/nircEHRModules/pull/47

#### Changes
* Add change to DefaultClinicalRemarksDataSource.getCategoryText
* Add lookupsets table info and QUS with cache refresh

2021-10-07 18:58 UTC, ankurjuneja approved these changes

2021-10-08 00:14 UTC, labkey-jeckels approved these changes

2021-10-08 15:48 UTC, labkey-jeckels requested changes

2021-10-08 15:48 UTC, labkey-jeckels commented on ehr/src/org/labkey/ehr/query/LookupSetsTable.java
> +        protected void afterInsertUpdate(int count, BatchValidationException errors)
For completeness should hook into deleteRows() as well. truncateRows() gets called when the whole table is being cleared, but won't be invoked for individual rows being deleted.

2021-10-08 16:51 UTC, labkey-martyp commented on ehr/src/org/labkey/ehr/query/LookupSetsTable.java
> +        protected void afterInsertUpdate(int count, BatchValidationException errors)
Good call, added.

2021-10-08 17:23 UTC, labkey-jeckels approved these changes

2021-10-08 21:23 UTC, merged