Cache only immutable collections
LabKey/ehrModules pull request #346
Opened 2022-03-29 21:46 UTC by labkey-jeckels

#### Rationale
New warnings in our caching layer pointed out the EHR code is caching mutable maps and sets. It's both thrilling and dangerous.

#### Changes
* Wrap collections in an unmodifiable layer before caching them

2022-03-29 21:56 UTC, labkey-adam requested changes
See comment on TriggerScriptHelper... I think new code will attempt to change an unmodifiable map.

2022-03-29 21:56 UTC, labkey-adam commented on ehr/src/org/labkey/ehr/utils/TriggerScriptHelper.java
>              }
I don't think `ret.put()` is going to work very well once `ret` is unmodifiable. I think you'll need a similar pattern to the below.

2022-03-29 23:51 UTC, labkey-jeckels commented on ehr/src/org/labkey/ehr/utils/TriggerScriptHelper.java
>              }
Fixed. Still a clunky approach to caching, but an incremental improvement.

2022-04-04 21:07 UTC, labkey-adam approved these changes

2022-04-04 21:08 UTC, merged