Modified program to add the remark values into the Urinalysis result …
LabKey/ehrModules pull request #425
Opened 2022-10-15 02:35 UTC by Ohsudev

Modified program to add the remark values into the Urinalysis result Full History reports.

#### Changes
*

2022-10-18 16:39 UTC, Ohsudev commented
Marty.  Can you please review this build, and onprc_ehr PR version of the same name.

2022-10-18 19:38 UTC, kollil approved these changes

2022-10-18 20:09 UTC, labkey-martyp requested changes
I think you can do this in onprc_ehr module without having to change the core ehr. Please try out the suggested change there.

2022-10-19 13:45 UTC, labkey-martyp commented
Changes made in onprc

2022-10-19 13:45 UTC, closed without merging