Initial @labkey/ehr setup and example
LabKey/ehrModules pull request #675
Opened 2023-10-13 14:30 UTC by labkey-martyp

#### Rationale
This creates the @labkey/ehr npm package and provides an example component and jest test. Also adds a usage example in EHR_App module with jest test.

#### Related Pull Requests
* https://github.com/LabKey/labkey-ui-components/pull/1315

#### Changes
* Add labkey-ui-ehr module
* NPM build for building, packaging and publish @labkey/ehr
* Jest set up with TeamCity integration
* Example component in @labkey/ehr with jest test
* Set up NPM build in EHR_App with @labkey/ehr as a dependency
* Example usage of @labkey/ehr component in EHR_App with jest test
* Lint setup
* Documentation

2023-10-13 20:17 UTC, cnathe requested changes

2023-10-13 20:17 UTC, cnathe commented on EHR_App/package.json
> +    "clean": "rimraf resources/web/jhu_ehr/gen && rimraf resources/views/gen && rimraf resources/web/gen",
I assume `jhu_ehr` isn't correct here?

2023-10-13 20:17 UTC, cnathe commented on labkey-ui-ehr/src/theme/index.scss
> +//@import "@labkey/components-app-scss/variables";
looking at the labkey-ui-premium equivalent of this file, I think you want the commented out line here and not the other one. Right?

2023-10-16 12:53 UTC, cnathe approved these changes

2023-10-18 00:42 UTC, labkey-martyp commented on EHR_App/package.json
> +    "clean": "rimraf resources/web/jhu_ehr/gen && rimraf resources/views/gen && rimraf resources/web/gen",
yes fixed, thank you

2023-10-20 04:21 UTC, merged