Refactor kinship to allow other code to initiate import directly
LabKey/ehrModules pull request #730
Opened 2024-02-28 15:03 UTC by bbimber

2024-02-28 23:27 UTC, bbimber commented
@labkey-martyp: this is a simplification of the earlier PR. There's a JHU postgres failure, but it does not seem related to the genetics calculations.

2024-03-04 11:53 UTC, labkey-martyp commented
Thanks @bbimber let me test this out on data from the centers, otherwise it looks good.

2024-03-04 14:53 UTC, bbimber commented
Thanks @labkey-martyp. Like I posted on the support thread, please keep in mind that you can just run populateKinship standalone, where you replace the TSV loading with RLabkey/SelectRows. That should make it quick to point to any accessible center's server (even a production server) to non-invasive testing on real data.

2024-03-11 05:00 UTC, labkey-martyp requested changes
Ok I tested this out across centers. Looks good with just a couple requests. Check them out, let me know if you have any follow up on them.

2024-03-11 05:00 UTC, labkey-martyp commented on ehr/src/org/labkey/ehr/pipeline/GeneticCalculationsImportTask.java
> +            if (Boolean.parseBoolean(getJob().getParameters().get("kinshipValidation")))
We're not adding this parameter in the job so this is never true. This can either go back to calling isKinshipValidation or add that value to the job parameters when it is created. Looks like that is in GeneticsCalculationsRunnable.

2024-03-11 05:00 UTC, labkey-martyp commented on ehr/resources/pipeline/kinship/populateKinship.r
> +    if (pctMissingSex > 0.25) {
This check is already being done in fixParents, and it's only throwing a warning there and still performing the calculations. I don't think we want to stray from that. I think we can remove this check.

2024-03-11 13:39 UTC, bbimber commented on ehr/resources/pipeline/kinship/populateKinship.r
> +    if (pctMissingSex > 0.25) {
I thought I remembered fixParents throwing, but if you tried this and it's a warning then you're probably fine.

2024-03-11 13:42 UTC, bbimber commented on ehr/src/org/labkey/ehr/pipeline/GeneticCalculationsImportTask.java
> +            if (Boolean.parseBoolean(getJob().getParameters().get("kinshipValidation")))
Yes, good point. I didnt back this out when I removed the other changes

2024-03-11 13:43 UTC, bbimber commented
Thanks @labkey-martyp. The last commit addresses those 2 comments.

2024-03-12 02:15 UTC, labkey-martyp approved these changes
Looks good. Thanks Ben.

2024-03-12 02:19 UTC, merged